### ISSUE TITLE
SvelteKit Error: "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by wiredprairie** [quilljs/quill#4038]
**Steps for Reproduction**

Create a basic SvelteKit demo app:
```
npm create svelte@latest bug-demo
```
Select: `Skeleton project (Barebones scaffolding for your new SvelteKit app)`
Select: `Yes, usingTypeScript syntax`
Ignore final options, just press [Enter]

Follow steps to complete:
```
Next steps:
  1: cd bug-demo
  2: npm install
  3. npm install quill@rc
```

Edit file: `/src/routes/+page.svelte`

```typescript
<script lang="ts">
	import 'quill/dist/quill.snow.css';
	import Quill from 'quill';
	import { onMount } from 'svelte';

	onMount(() => {
		const quill = new Quill('#editor', {
			theme: 'snow'
		});
	});
</script>

<main>
	<div id="editor"></div>
</main>
```

Start web app with `npm run dev`

Open browser, `localhost:5173`

**Expected behavior**:
Quill editor shows.

**Actual behavior**:
Error occurs:

```
3:10:23 PM [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "quill"
|- D:\Dev\bug-demo\node_modules\quill\quill.js:1
import Quill from './core';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

**Platforms**:
Edge: Version 122.0.2365.52 (Official build) (64-bit)
Windows Version 23H2 OS Build 22631.3155

**Version**:
2.0RC2

What's strange that I cannot explain is that SvelteKit uses Vite for most of its bundling, etc. (which uses Rollup internally).  But, in a simple Vite test (much like above), a basic Vite setup using just a plain Svelte web page works. It's only when the SvelteKit moving parts are involved. 

I've not used any CJS modules with my Sveltekit project so I've not seen this before. I know ESM is preferred for Vite and SvelteKit.

**Comment by konstantinblaesi** [comment]
I think the [quilljs package.json](https://www.npmjs.com/package/quill?activeTab=code) should state type = module if it uses imports

**Comment by vinodgubbala** [comment]
Similar error when used in jest (testing library), after trying to upgrade to `2.0.0-rc.2`

```
   Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

   /node_modules/quill/quill.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import Quill from './core';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import Quill from 'quill';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
```

**Comment by Gervwyk** [comment]
Same error running this in a pnpm monorepo.

**Comment by luin** [comment]
Fixed the bundle format in 2.0.0-rc.3

**Comment by vinodgubbala** [comment]
I can confirm my issue is fixed with `2.0.0-rc.3` .
I also had to add this configuration if someone come across this.

package.json
```json
"jest": {
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\](?!quill|lodash|parchment).+\\.(js|jsx|mjs|cjs|ts|tsx)$",
      "^.+\\.module\\.(css|sass|scss)$"
    ]
  }
```

**Comment by luin** [comment]
Closing as resolved.

**Comment by gitneeraj** [comment]
This is still a problem in v2.0.2

Facing the same issue when running the test `yarn test`.

I have replicated the issue at https://github.com/gitneeraj/test-quill-rte Please help!!

**Comment by vinodgubbala** [comment]
@gitneeraj did you try my solution?

**Comment by oleh-kazban-gl** [comment]
> @gitneeraj did you try my solution?

I've tried, is not working

**Comment by gilsonviana** [comment]
Any update on this?
