### ISSUE TITLE
TypeError: leaf.position is not a function

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#740]
I saw the following error several times.
I'll try to reproduce it while writing the deltas in the console.

```
TypeError: leaf.position is not a function
var _leaf$position5 = leaf.position(offset, i !== 0);
quill.js (line 5199, col 36)
```

**Steps for Reproduction**
1. Visit http://beta.quilljs.com/docs/formats/
2. Try random combinations of font, size, bold and H<sub>1</sub> until you get the TypeError

**Platforms**:
Firefox 47 on Windows 7

**Version**:
1.0-beta.4

**Comment by jhchen** [comment]
Can you post a stack trace next time you encounter it?

**Comment by benbro** [comment]
I saw the error several times but I'm not able to reproduce it again.
Closing for now.

**Comment by sachinrekhi** [comment]
I just encountered this issue myself in Quill 1.0 Beta 6.

bundle.js:43989 Uncaught TypeError: leaf.position is not a function

This occurs in quill.getBounds()
(more specifically within call to this.selection.getBounds() within quill.getBounds() call.

Pic of exact offending line here:

![screen shot 2016-06-21 at 3 48 26 pm](https://cloud.githubusercontent.com/assets/192650/16248996/e438f4f2-37c7-11e6-9008-dc167455b10a.png)

**Comment by jhchen** [comment]
Are you defining custom leaf blots? The line above makes sure `leaf` is not `null` so it's something that doesn't implement `position`, which should be inherited by Parchment's Leaf blot. It could also be that the structure is messed up because `scroll.leaf` just gets the deepest blot, assuming it is a Leaf which should be a safe assumption.

**Comment by sachinrekhi** [comment]
Nope, not yet using any custom blots in the current implementation where I encountered this error. Though possible that some of the other issues I filed were root causes for the structure getting messed up.

**Comment by sachinrekhi** [comment]
I'm consistently getting this error now. I set a breakpoint and here is what the local variables are. It looks like the leaf object is of type Break.

![screen shot 2016-06-23 at 5 09 23 pm](https://cloud.githubusercontent.com/assets/192650/16324100/96b4ad58-3965-11e6-9c4b-3da4765efe62.png)

**Comment by sachinrekhi** [comment]
For my case, a workaround that seems to be working is calling quill.update() explicitly before calling quill.getBounds()

My guess at maybe what is going on is that quill is in the middle of creating the new dom nodes for a updateContents() call made just before, and then the getBounds() is being call in the middle of it, resulting it it picking up a non-leaf node via scroll.leaf.

**Comment by jhchen** [comment]
This is probably fixed with 3b2167f8d6d8d23a848d72cd50ebc216574e2111 but without reproduction steps I can't be certain. The symptoms look the same though.

**Comment by sachinrekhi** [comment]
Yup, looks like that did the trick! Thanks

**Comment by Poizd** [comment]
*Reproducible*
Quill Editor v1.3.6

*Platforms:*
Windows 10, 
GCH Version 69.0.3497.100
FF 62.0.3 
IE11, EDGE

*Link where tested*
https://quilljs.com/playground/#autosave

*Steps*
1.  Add any link f.e 
http://en.wikipedia.org/wiki/One_Ring
2. Set Mouse pointer to the end of link, right after ..._Ring
3. Select any btn with styling (f.e. underscore text, or other color)
4. Click somewhere on link text http://en.wikipedia.org/wiki/One_Ring

WB: Uncaught TypeError: leaf.position is not a function
`  var _leaf$position3 = leaf.position(offset, true);
`
![image](https://user-images.githubusercontent.com/43962632/46616286-dc4a8d00-cb22-11e8-8657-48513ef59771.png)

**Comment by itspauloroberto** [comment]
I did make sure that i am using 3b2167f on my repository and the bug still occurs.

I have a consistent way to reproduce this error:

1. Click the editor to get the focus.
2. Type "A".
3. Hit [Enter] to create a new line.
3. Hold [Shift] and click [Arrow Left] on keyboard.
4. Boom!

**Comment by ryanhaney** [comment]
I also experience a similar error, "leaf.position is not a function". Interestingly, it also involves an arrow keypress, but in my case, it's the down arrow. I'm not sure why in some cases `leaf.position` is not a function. _If someone from the quill team would like to reach out to me, I'd be happy to set up a live demo to see if we can narrow it down._

I've addressed this in a hack that seems to work for me here: https://github.com/1010data/quill/commit/03f3b6f73840425f0cf61f4983ca3b0ef9b69383

Note that this is based off the 1.3.6 branch. If someone with this issue wants to test, you can use the "quill-leaf-fix" npm package. Note that you'll have to change your quill import/require statements to use 'quill-leaf-fix' instead, or figure out some other clever approach.

**Comment by divyanalluri** [comment]
This is probably fixed with [3b2167f](https://github.com/1010data/quill/commit/03f3b6f73840425f0cf61f4983ca3b0ef9b69383) but without reproduction steps I can't be certain. The symptoms look the same though.

**Comment by divyanalluri** [comment]
Is this commit [3b2167f](https://github.com/1010data/quill/commit/03f3b6f73840425f0cf61f4983ca3b0ef9b69383) merged to the latest version ..
